INSERT INTO `league` VALUES (0,'France','French League 1');
INSERT INTO `league` VALUES (0,'Germany','Bundesliga');
INSERT INTO `league` VALUES (0,'India','ISL');
INSERT INTO `league` VALUES (0,'England','EPL');
INSERT INTO `league` VALUES (0,'Italy','Serie A');
INSERT INTO `league` VALUES (0,'Spain','La Liga');

INSERT INTO `football_club` VALUES (0,'FC Barcelona','61',86,6);
INSERT INTO `football_club` VALUES (0,'Real Madrid', '62',85,6);
INSERT INTO `football_club` VALUES (0,'Atletico Madrid','63',82,6);
INSERT INTO `football_club` VALUES (0,'Sevilla','64',75,6);
INSERT INTO `football_club` VALUES (0,'Granada','65',54,6);
INSERT INTO `football_club` VALUES (0,'Villareal','66',67,6);
INSERT INTO `football_club` VALUES (0,'Eibar','67',68,6);
INSERT INTO `football_club` VALUES (0,'Liverpool','41',85,4);
INSERT INTO `football_club` VALUES (0,'Manchester City','42',85,4);
INSERT INTO `football_club` VALUES (0,'Manchester United','43',75,4);
INSERT INTO `football_club` VALUES (0,'Arsenal','44',78,4);
INSERT INTO `football_club` VALUES (0,'Chelsea','45',79,4);
INSERT INTO `football_club` VALUES (0,'Leicester','46',78,4);
INSERT INTO `football_club` VALUES (0,'Marselle','11',85,1);
INSERT INTO `football_club` VALUES (0,'PSG','12',78,1);
INSERT INTO `football_club` VALUES (0,'Lille','13',75,1);
INSERT INTO `football_club` VALUES (0,'Angers','14',75,1);
INSERT INTO `football_club` VALUES (0,'Bayern Munich','21',86,2);
INSERT INTO `football_club` VALUES (0,'Berlin','22',69,2);
INSERT INTO `football_club` VALUES (0,'Leverusken','23',87,2);
INSERT INTO `football_club` VALUES (0,'Hoffenheim','24',82,2);
INSERT INTO `football_club` VALUES (0,'Wolfsburg','25',81,2);
INSERT INTO `football_club` VALUES (0,'Dortmund','26',80,2);
INSERT INTO `football_club` VALUES (0,'Juventus','51',84,5);
INSERT INTO `football_club` VALUES (0,'Inter Milan','52',86,5);
INSERT INTO `football_club` VALUES (0,'AC Milan','53',73,5);
INSERT INTO `football_club` VALUES (0,'Lazio','54',75,5);
INSERT INTO `football_club` VALUES (0,'Atlanta','55',78,5);
INSERT INTO `football_club` VALUES (0,'ATK','31',76,3);
INSERT INTO `football_club` VALUES (0,'Goa','32',54,3);
INSERT INTO `football_club` VALUES (0,'Jamshedpur','33',55,3);
INSERT INTO `football_club` VALUES (0,'Northeast','34',59,3);
INSERT INTO `football_club` VALUES (0,'Bengaluru','35',68,3);

INSERT INTO `football_player` VALUES (0, 42, 1, 92, 'Argentina', 'Lionel Messi',32);
INSERT INTO `football_player` VALUES (0, 40, 2, 90, 'Portugal', 'C. Ronaldo',34);
INSERT INTO `football_player` VALUES (0, 22, 15, 85, 'Brazil', 'Neymar Jr.',27);
INSERT INTO `football_player` VALUES (0, 10, 1, 83, 'Spain', 'Gerard Pique',32);
INSERT INTO `football_player` VALUES (0, 20, 9, 83, 'Belgium', 'Kevin De B.',28);
INSERT INTO `football_player` VALUES (0, 18, 18, 83, 'Poland', 'Robert L.',31);
INSERT INTO `football_player` VALUES (0, 18, 3, 80, 'Brazil', 'Alisson', 30);
INSERT INTO `football_player` VALUES (0, 18, 4, 80, 'England', 'Nathaniel Clyne', 30);
INSERT INTO `football_player` VALUES (0, 18, 5, 80, 'Brazil', 'Fabinho', 30);
INSERT INTO `football_player` VALUES (0, 18, 6, 80, 'Netherlands', 'Virgil Dijk', 30);
INSERT INTO `football_player` VALUES (0, 18, 7, 80, 'Netherlands', 'George Landum', 30);
INSERT INTO `football_player` VALUES (0, 18, 8, 80, 'Croatia', 'Dejan Lovren', 30);
INSERT INTO `football_player` VALUES (0, 18, 9, 80, 'England', 'James Milner', 30);
INSERT INTO `football_player` VALUES (0, 18, 10, 80, 'Guinea', 'Naby Keïta', 30);
INSERT INTO `football_player` VALUES (0, 18, 11, 80, 'Brazil', 'Roberto Firmino', 30);
INSERT INTO `football_player` VALUES (0, 18, 12, 80, 'Senegal', 'Sadio Mané', 30);
INSERT INTO `football_player` VALUES (0, 18, 13, 80, 'Egypt', 'Mohamed Salah', 30);
INSERT INTO `football_player` VALUES (0, 18, 14, 80, 'England', 'Joe Gomez', 30);
INSERT INTO `football_player` VALUES (0, 18, 15, 80, 'Spain', 'Adrián', 30);
INSERT INTO `football_player` VALUES (0, 18, 16, 80, 'England','Jordan Henderson', 30);
INSERT INTO `football_player` VALUES (0, 17, 17, 75, 'Chile', 'Claudio Bravo', 28);
INSERT INTO `football_player` VALUES (0, 17, 18, 75, 'England', 'Kyle Walker', 28);
INSERT INTO `football_player` VALUES (0, 17, 19, 75, 'England', 'John Stones', 28);
INSERT INTO `football_player` VALUES (0, 17, 20, 75, 'England', 'Raheem Sterling', 28);
INSERT INTO `football_player` VALUES (0, 17, 21, 75, 'Germany', 'Ilkay Gundogan', 28);
INSERT INTO `football_player` VALUES (0, 17, 22, 75, 'Brazil',   'Gabriel Jesus', 28);
INSERT INTO `football_player` VALUES (0, 17, 23, 75, 'Argentina','Sergio Agüero', 28);
INSERT INTO `football_player` VALUES (0, 16, 24, 75, 'Ukraine',	'Oleksandr Zinchenko', 28);
INSERT INTO `football_player` VALUES (0, 16, 25, 75, 'Spain',				'Angeliño', 28);
INSERT INTO `football_player` VALUES (0, 16, 26, 75, 'France', 				'Aymeric Laporte', 28);
INSERT INTO `football_player` VALUES (0, 16, 27, 75, 'Spain',				'Rodrigo', 28);
INSERT INTO `football_player` VALUES (0, 16, 28, 75, 'Algeria',	 			'Riyad Mahrez', 28);
INSERT INTO `football_player` VALUES (0, 16, 29, 75, 'Portugal', 			'João Cancelo', 28);
INSERT INTO `football_player` VALUES (0, 16, 30, 75, 'Argentina', 			'Nicolás Otamendi', 28);
INSERT INTO `football_player` VALUES (0, 16, 31, 75, 'Brazil', 	    		'Ederson', 28);
INSERT INTO `football_player` VALUES (0, 16, 32, 75, 'England',	 			'Daniel Grimshaw', 28);
INSERT INTO `football_player` VALUES (0, 16, 33, 75, 'Netherlands', 			'Frenkie de Jong', 28);
INSERT INTO `football_player` VALUES (0, 15, 1, 75, 'Chile',				'Arturo Vidal', 28);
INSERT INTO `football_player` VALUES (0, 15, 2, 75, 'France',	 			'Samuel Umtiti', 28);
INSERT INTO `football_player` VALUES (0, 15, 3, 75, 'Spain',				'Junior Firpo', 28);
INSERT INTO `football_player` VALUES (0, 15, 4, 75, 'France', 				'Clément Lenglet', 28);
INSERT INTO `football_player` VALUES (0, 15, 5, 75, 'Senegal',	 			'Moussa Wagué', 28);
INSERT INTO `football_player` VALUES (0, 15, 6, 75, 'France', 				'Antoine Griezmann', 28);
INSERT INTO `football_player` VALUES (0, 15, 7, 75, 'Spain',				'Jordi Alba', 28);
INSERT INTO `football_player` VALUES (0, 15, 8, 75, 'Spain',				'Carles Aleñá', 28);
INSERT INTO `football_player` VALUES (0, 15, 9, 75, 'Brazil', 				'Casemiro', 28);
INSERT INTO `football_player` VALUES (0, 15, 10, 75, 'Uruguay',	 			'Federico Valverde', 28);
INSERT INTO `football_player` VALUES (0, 15, 11, 75, 'Colombia', 	 		'James Rodríguez', 28);
INSERT INTO `football_player` VALUES (0, 15, 12, 75, 'Spain','Lucas Vazquez', 28);
INSERT INTO `football_player` VALUES (0, 14, 13, 75, 'Serbia', 'Luka Jovic', 28);
INSERT INTO `football_player` VALUES (0, 14, 14, 75, 'Spain','Álvaro Odriozola', 28);
INSERT INTO `football_player` VALUES (0, 14, 15, 75, 'Spain','Marco Asensio', 28);
INSERT INTO `football_player` VALUES (0, 14, 16, 75, 'Spain','Brahim Díaz', 28);
INSERT INTO `football_player` VALUES (0, 14, 17, 75, 'Spain','Isco', 28);
INSERT INTO `football_player` VALUES (0, 14, 18, 75, 'France', 'Ferland Mendy', 28);
INSERT INTO `football_player` VALUES (0, 14, 19, 75, 'Dominican Republic', 'Mariano Díaz', 28);
INSERT INTO `football_player` VALUES (0, 13, 20, 75, 'Brazil', 'Vinícius Júnior', 28);
INSERT INTO `football_player` VALUES (0, 13, 21, 75, 'Brazil', 'Rodrygo', 28);
INSERT INTO `attacker` VALUES (1 , 17);
INSERT INTO `attacker` VALUES (2 , 59);
INSERT INTO `attacker` VALUES (3 , 83);
INSERT INTO `attacker` VALUES (4 , 68);
INSERT INTO `attacker` VALUES (5 , 40);
INSERT INTO `attacker` VALUES (6 , 82);
INSERT INTO `attacker` VALUES (7 , 54);
INSERT INTO `attacker` VALUES (8 , 88);
INSERT INTO `attacker` VALUES (9 , 33);
INSERT INTO `attacker` VALUES (10 , 19);
INSERT INTO `attacker` VALUES (11 , 50);
INSERT INTO `attacker` VALUES (12 , 75);
INSERT INTO `attacker` VALUES (13 , 102);
INSERT INTO `attacker` VALUES (14 , 52);
INSERT INTO `attacker` VALUES (15 , 97);
INSERT INTO `attacker` VALUES (16 , 13);
INSERT INTO `attacker` VALUES (17 , 37);
INSERT INTO `attacker` VALUES (18 , 39);
INSERT INTO `attacker` VALUES (19 , 50);
INSERT INTO `defender` VALUES (20 , 22);
INSERT INTO `defender` VALUES (21 , 13);
INSERT INTO `defender` VALUES (22 , 79);
INSERT INTO `defender` VALUES (23 , 19);
INSERT INTO `defender` VALUES (24 , 67);
INSERT INTO `defender` VALUES (25 , 70);
INSERT INTO `defender` VALUES (26 , 43);
INSERT INTO `defender` VALUES (27 , 109);
INSERT INTO `defender` VALUES (28 , 88);
INSERT INTO `defender` VALUES (29 , 26);
INSERT INTO `defender` VALUES (30 , 45);
INSERT INTO `defender` VALUES (31 , 107);
INSERT INTO `defender` VALUES (32 , 36);
INSERT INTO `defender` VALUES (33 , 22);
INSERT INTO `defender` VALUES (34 , 77);
INSERT INTO `defender` VALUES (35 , 20);
INSERT INTO `defender` VALUES (36 , 43);
INSERT INTO `defender` VALUES (37 , 89);
INSERT INTO `defender` VALUES (38 , 59);
INSERT INTO `defender` VALUES (39 , 89);
INSERT INTO `defender` VALUES (40 , 31);
INSERT INTO `defender` VALUES (41 , 77);
INSERT INTO `defender` VALUES (42 , 82);
INSERT INTO `defender` VALUES (43 , 103);
INSERT INTO `defender` VALUES (44 , 46);
INSERT INTO `defender` VALUES (45 , 95);
INSERT INTO `defender` VALUES (46 , 55);
INSERT INTO `midfielder` VALUES (47 , 38);
INSERT INTO `midfielder` VALUES (48 , 101);
INSERT INTO `midfielder` VALUES (49 , 104);
INSERT INTO `midfielder` VALUES (50 , 67);
INSERT INTO `midfielder` VALUES (51 , 11);
INSERT INTO `goalkeeper` VALUES (52 , 63);
INSERT INTO `goalkeeper` VALUES (53 , 18);
INSERT INTO `goalkeeper` VALUES (54 , 54);
INSERT INTO `goalkeeper` VALUES (55 , 78);
INSERT INTO `goalkeeper` VALUES (56 , 100);
INSERT INTO `goalkeeper` VALUES (57 , 34);
INSERT INTO `goalkeeper` VALUES (58 , 106);
